export const CONVERSATIONAL_KEYWORDS: string[] = [
  '방금',
  '이전',
  '질문',
  '대화',
  '했지',
  '했었지',
  '물어봤지',
  '뭐였지',
  'previous',
  'last question',
  'conversation',
  'what did i just ask',
  'what did i just answer',
  'what did i just note',
  'what was my last question',
  'what was my last answer',
  'what was my last note',
  'what was my last conversation',
  'what was my last question',
  'what was my last answer',
  'what was my last note',
  'what was my last conversation',
  'just asked',
  'just answered',
  'just noted',
  'in this session',
  'session',
  'what was my',
  'tell me about',
  'who are you',
  'what can you do',
  'help me',
  'did i ask',
  'history',
  'record',
];
