export const OUTCOME_KEYWORDS: Record<string, string[]> = {
  FAILED: [
    'failed',
    'failure',
    'error',
    'errors',
    'exception',
    'timeout',
    'broken',
    'down',
    'issue',
    'problem',
  ],
  SUCCESS: ['success', 'succeeded', 'working', 'ok'],
  WARNING: [
    'slow',
    'latency',
    'warning',
    'degraded',
    'slow response',
    'slow performance',
    'slow network',
    'slow database',
    'slow API',
    'slow service',
  ],
  EDGE_CASE: [
    'edge case',
    'edge',
    'unknown',
    '특별한',
    'rare',
    'unusual',
    'rare event',
    'unusual event',
    'rare case',
    'unusual case',
    'rare scenario',
    'unusual scenario',
    'rare situation',
    'unusual situation',
  ],
  ANY: ['any'],
  NONE: ['none'],
};
